version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: strategy-client-dev
    ports:
      - "9011:9010" # Porta padrão do Quasar dev server
    volumes:
      # Montar código fonte para hot reload
      - .:/app
      # Persistir node_modules em volume nomeado para melhor performance
      - node_modules_client:/app/node_modules
    env_file:
      - .env # Carregar variáveis do arquivo .env
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Para funcionar melhor com hot reload no Docker
    extra_hosts:
      - "host.docker.internal:host-gateway" # Para acessar serviços do host
    stdin_open: true
    tty: true
    command: npm run dev
    networks:
      - strategy-network-dev

volumes:
  node_modules_client:

networks:
  strategy-network-dev:
    driver: bridge
