version: "3.8"

services:
  quasar-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9010:80"
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NODE_ENV=production
